---
tap_install:
  values:
    profile: run
    ceip_policy_disclosed: true 
    shared:
      ingress_domain: run-prod.prep.tapsme.org
      ingress_issuer: letsencrypt-production
    supply_chain: basic
    contour:
      envoy:
        service:
          type: LoadBalancer
    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.view.prep.tapsme.org
    namespace_provisioner:
      controller: false
      additional_sources:
      - git:
          url: ssh://git@github.com/Mpluya/tap-namespaces
          ref: origin/main
          subPath: credentials
          secretRef:
            name: sync-git-ssh-also
            namespace: tanzu-sync
            create_export: true
        path: _ytt_lib/workload-creds
      gitops_install:
        ref: origin/main
        subPath: ns-provisioner-base
        url: ssh://git@github.com/Mpluya/tap-namespaces
        secretRef:
          name: sync-git-ssh
          namespace: tanzu-sync
          create_export: true
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true
    api_auto_registration:
      tap_gui_url: "https://tap-gui.view.prep.tapsme.org"
      cluster_name: run-prod
    excluded_packages:
    - bitnami.services.tanzu.vmware.com
    - external-secrets.apps.tanzu.vmware.com