#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-cluster-issuer-secret
  namespace: tap-install
spec:
  secretStoreRef:
    name: tenant-secret-store
    kind: SecretStore
  refreshInterval: "1m"
  target:
    type: kubernetes.io/tls
  data:
    - secretKey: ca.crt
      remoteRef: #@ data.values.tap_install.secrets.eso.remote_refs.tap_sensitive_values.ca_cluster_issuer_values.ca_cert
    - secretKey: ca.key
      remoteRef: #@ data.values.tap_install.secrets.eso.remote_refs.tap_sensitive_values.ca_cluster_issuer_values.ca_key