---
tap_install:
  values:
    profile: view
    ceip_policy_disclosed: true

    shared:
      ingress_domain: view.success.tapsme.org
      ingress_issuer: letsencrypt-production

    contour:
      infrastructure_provider: aws
      envoy:
        service:
          type: LoadBalancer

    api_portal:
      apiPortalServer:
        sourceUrls: "https://customer-profile-too.mae.run.prep.tapsme.org/api-docs,https://scg-openapi.run.prep.tapsme.org/openapi"
      sso:
        enabled: true
        secretName: api-portal-sso-credentials
      apiKey:
        enabled: true
        vault:
          url: "https://vault.view.cssa.tapsme.org/"        # Required: You may use "http://vault.vault.svc:8200/" if Vault is installed in the same cluster as API portal
          role: api-portal-role        # Required: Same as the role name you created in the previous step
          path: api-portal-for-vmware-tanzu # Optional: defaults to `api-portal-for-vmware-tanzu` if not specified. Make sure to use the same path you created and configured in the previous steps

      serviceAccount:
        create: false      # You may set it to false if you'd like to create the service account manually
        name: api-portal-sa  # Defaults to `default` if not specified

    tap_gui:
      metadataStoreAutoconfiguration: true
      service_type: ClusterIP
      app_config:
        permission:
          enabled: false
          adminRefs:
            - user:default/x95castle1
            - user:default/mpluya
            - user:default/maelarge@gmail.com
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: 735ec722b8914b709330
                clientSecret: pooooo
        organization:
          name: "Global Tech Team"
        catalog:
          locations:
            - type: url
              target: https://github.com/maelarge/tap-catalog/blob/main/catalog-info.yaml                  
    
    appliveview:
      ingressEnabled: true
      ingress_issuer: letsencrypt-production

    metadata_store:
      ingress_enabled: "true"
      app_service_type: "ClusterIP"
      ns_for_export_app_cert: "*"