---
tap_install:
  values:
    profile: view
    ceip_policy_disclosed: true

    shared:
      ingress_domain: view.success.tapsme.org

    contour:
      infrastructure_provider: aws
      envoy:
        service:
          type: LoadBalancer
    tap_gui:
      metadataStoreAutoconfiguration: true
      service_type: ClusterIP
      app_config:
        permission:
          enabled: true
          adminRefs:
            - user:default/x95castle1
            - user:default/rabeyta
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: 735ec722b8914b709330
                clientSecret: pooooo
        organization:
          name: "Global Tech Team"
        catalog:
          locations:
            - type: url
              target: https://github.com/maelarge/tap-catalog/blob/main/catalog-info.yaml                  

    appliveview:
      ingressEnabled: true
      ingress_issuer: letsencrypt-staging

    accelerator:
      ingress:
        include: true

    metadata_store:
      ingress_enabled: "true"
      app_service_type: "ClusterIP"
      ns_for_export_app_cert: "*"