#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-services-values
  namespace: tap-install
stringData:
  values.yaml: |
    postgresql:
      enabled: true
      region: "us-west-2"
      provider_config_ref:
        name: "provider-aws-rds"
      infrastructure:
        subnet_group:
          name: "aws-services-db-subnet-group"
        security_groups:
          - id: "sg-024580a8093a527fd"
      instance_configuration:
        instance_class: "db.t3.micro"
        engine_version: "13.7"
        skip_final_snapshot: true
        publicly_accessible: true
