apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-secrets
  namespace: tap-install
spec:
  secretStoreRef:
    name: tenant-secret-store
    kind: SecretStore
  refreshInterval: "1m"
  data:
  - secretKey: tenant-secrets.yaml
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
    