apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
  name: application-configuration-service
  namespace: tap-install
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: application-configuration-service.tanzu.vmware.com
    versionSelection:
      constraints: 2.1.1
      prereleases: {}