apiVersion: v1
kind: Secret
metadata:
  name: config-overlays
  namespace: tap-install #! namespace where tap is installed
stringData:
  config-overlays.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"ConfigMap","metadata":{"name":"config-features"}})
    ---
    data:
      #@overlay/match missing_ok=True
      kubernetes.podspec-tolerations: enabled
      #@overlay/match missing_ok=True
      kubernetes.podspec-affinity: enabled
  
    #@overlay/match by=overlay.subset({"kind":"ConfigMap","metadata":{"name":"config-gc"}})
    ---
    data:
      #@overlay/match missing_ok=True
      min-non-active-revisions: "0"
      #@overlay/match missing_ok=True
      max-non-active-revisions: "0"
      #@overlay/match missing_ok=True
      retain-since-create-time: "disabled"
      #@overlay/match missing_ok=True
      retain-since-last-active-time: "disabled"