apiVersion: v1
kind: Secret
metadata:
  name: config-gc-overlay
  namespace: tap-install
stringData:
  config-features-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"ConfigMap","metadata":{"name":"config-gc"}})
    ---
    data:
      #@overlay/match missing_ok=True
      min-non-active-revisions: "0"
      #@overlay/match missing_ok=True
      max-non-active-revisions: "0"
      #@overlay/match missing_ok=True
      retain-since-create-time: "disabled"
      #@overlay/match missing_ok=True
      retain-since-last-active-time: "disabled"