apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-secrets
  namespace: tap-install
spec:
  secretStoreRef:
    name: tenant-secret-store
    kind: SecretStore
  refreshInterval: "0m"
  target:
    type: kubernetes.io/ssh-auth
  data:
  - secretKey: known_hosts
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: known_hosts
  - secretKey: ssh_privatekey
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: ssh_privatekey
  - secretKey: identity
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: ssh_privatekey
    