#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: install-registry-dockerconfig
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: tanzu-sync-secrets
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore"
    kapp.k14s.io/change-rule.1: "delete before deleting eso/secretstore"
spec:
  secretStoreRef:
    name: tanzu-sync-secrets
    kind: SecretStore
  refreshInterval: "1m"
  target:
    type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef: #@ data.values.secrets.eso.remote_refs.install_registry_dockerconfig.dockerconfigjson
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: tap-gui
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: tap-gui
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: api-portal
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: api-portal
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: metadata-store
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: metadata-store
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: app-live-view
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: app-live-view
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: accelerator-system
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: accelerator-system
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: tap-registry