apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: mae-api-gateway
  namespace: mae
  annotations:
    apis.tanzu.vmware.com/api-title: 'My Exciting APIs'
    apis.tanzu.vmware.com/api-description: 'Lots of new exciting APIs for you to use!'
    apis.tanzu.vmware.com/api-documentation: 'https://docs.example.org'
  labels:
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8090"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway
    tanzu.app.live.view.application.actuator.path: actuator
    tanzu.app.live.view.application.name: mae-api-gateway
spec:
  count: 1
  observability:
    metrics:
      prometheus:
        enabled: true
  serviceAccount:
    name: gateway-sa
  extensions:
    secretsProviders:
      - name: vault-api-keys
        vault:
          roleName: gateway-role
          path: api-portal-for-vmware-tanzu
    filters:
      apiKey:
        enabled: false
        secretsProviderName: vault-api-keys