---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: mae-gateway-routes
  namespace: mae
spec:
  routes:
    - uri: https://customer-profile.mae.run.prep.tapsme.org
      predicates:
        - Path=/poo/**
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: mae-gateway-mapping
  namespace: mae
spec:
  gatewayRef:
    name: mae-api-gateway
  routeConfigRef:
    name: mae-gateway-routes