---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: mae-gateway-routes
  namespace: mae
spec:
  routes:
    - uri: https://customer-profile.mae.run.prep.tapsme.org
      openapi:
        generation:
          enabled: true
      predicates:
        - Path=/poo/**
    - uri: https://httpbingo.org
      openapi:
        generation:
          enabled: true
      predicates:
        - Path=/bingo/**
      filters:
      - RateLimit=1,10s,{IPs:100;70.163.251.107}
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: mae-gateway-mapping
  namespace: mae
spec:
  gatewayRef:
    name: mae-api-gateway
  routeConfigRef:
    name: mae-gateway-routes