---
tap_install:
  secrets:
    eso:
      aws:
        region: us-west-2
        tap_install_secrets:
          role_arn: arn:aws:iam::692116071922:role/cg-eks-run-prod--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: dev/cg-eks-run-prod/tap/sensitive-values.yaml
