tap_install:
  package_repository:
    oci_repository: registry.harbor.learn.tapsme.org/tap/tap-packages
  version:
    package_repo_bundle_tag: "1.7.0-rc.3" # Populate these values with the latest patch version.
    package_version: "1.7.0-rc.3"