---
tap_install:
  values:
    profile: run
    ceip_policy_disclosed: true 
    shared:
      ingress_domain: run.prep.tapsme.org
      ingress_issuer: letsencrypt-production
    supply_chain: basic
    amr:
      observer:
        cloudevent_handler:
          endpoint: "https://amr-cloudevent-handler.view.success.tapsme.org"
          liveness_period_seconds: 10
        auth:
          kubernetes_service_accounts:
            enable: true
            autoconfigure: true
            secret:
              ref: "amr-observer-editor-token"
    contour:
      envoy:
        service:
          type: LoadBalancer
    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.view.success.tapsme.org
    namespace_provisioner:
      controller: false
      additional_sources:
      - git:
          url: ssh://git@github.com/Mpluya/tap-namespaces
          ref: origin/main
          subPath: credentials
          secretRef:
            name: sync-git
            namespace: tanzu-sync
        path: _ytt_lib/workload-creds
      - git:
          url: ssh://git@github.com/Mpluya/tap-namespaces
          ref: origin/main
          subPath: additional-resources-run
          secretRef:
            name: sync-git
            namespace: tanzu-sync
        path: _ytt_lib/addons      
      gitops_install:
        ref: origin/main
        subPath: ns-provisioner-base
        url: ssh://git@github.com/Mpluya/tap-namespaces
        secretRef:
          name: sync-git
          namespace: tanzu-sync
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true
    api_auto_registration:
      tap_gui_url: "https://tap-gui.view.success.tapsme.org"
      cluster_name: run
    excluded_packages:
    - external-secrets.apps.tanzu.vmware.com
        
    package_overlays:
    - name: "cnrs"
      secrets: 
      - name: "config-overlays"